In [46]:
import numpy as np

## Indexing

In [48]:
a = np.arange(1,8)
a

array([1, 2, 3, 4, 5, 6, 7])

In [49]:
a[-1]

7

In [50]:
a[[-1, 0, 2]]

array([7, 1, 3])

In [52]:
arr = np.arange(1,7).reshape(3,2)
arr

array([[1, 2],
       [3, 4],
       [5, 6]])

In [53]:
arr[1, 1]

4

In [54]:
arr[-1]

array([5, 6])

In [55]:
arr[:, 0]

array([1, 3, 5])

In [56]:
arr3 = np.arange(1,19).reshape(3,2,3)
arr3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [57]:
arr3[1]

array([[ 7,  8,  9],
       [10, 11, 12]])

In [58]:
arr3[-1, 0]

array([13, 14, 15])

In [60]:
arr3[0, :, :2]

array([[1, 2],
       [4, 5]])

## Slicing

In [61]:
a

array([1, 2, 3, 4, 5, 6, 7])

In [63]:
a[3:6]

array([4, 5, 6])

In [64]:
arr

array([[1, 2],
       [3, 4],
       [5, 6]])

In [65]:
arr[1:, :]

array([[3, 4],
       [5, 6]])

In [66]:
arr[:, 1]

array([2, 4, 6])

In [67]:
arr

array([[1, 2],
       [3, 4],
       [5, 6]])

In [68]:
arr3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [70]:
arr3[0, :, [-1, 0]]

array([[3, 6],
       [1, 4]])

## Modifying the data in Numpy

In [71]:
a

array([1, 2, 3, 4, 5, 6, 7])

In [73]:
a[-1] = 0

In [74]:
a

array([1, 2, 3, 4, 5, 6, 0])

In [75]:
a[[0, -1, -3]] = -2

In [76]:
a

array([-2,  2,  3,  4, -2,  6, -2])

In [77]:
a[[0, -1, -3]] = [10, 20, 30]
a

array([10,  2,  3,  4, 30,  6, 20])

In [78]:
arr

array([[1, 2],
       [3, 4],
       [5, 6]])

In [81]:
arr[0] = -1
arr

array([[-1, -1],
       [ 3,  4],
       [ 5,  6]])

In [82]:
arr[0] = [5,6]

In [83]:
arr

array([[5, 6],
       [3, 4],
       [5, 6]])

In [85]:
arr[:2, :] = 0
arr

array([[0, 0],
       [0, 0],
       [5, 6]])

In [86]:
arr[:2, :] = np.arange(4).reshape(2,2)
arr

array([[0, 1],
       [2, 3],
       [5, 6]])

In [88]:
arr[:2, :] = [8,9]
arr

array([[8, 9],
       [8, 9],
       [5, 6]])

In [89]:
a

array([10,  2,  3,  4, 30,  6, 20])

In [91]:
np.where( a < 4, a, -1)

array([-1,  2,  3, -1, -1, -1, -1])

In [93]:
arr

array([[8, 9],
       [8, 9],
       [5, 6]])

In [94]:
np.where( arr == 9, -9, arr+1)

array([[ 9, -9],
       [ 9, -9],
       [ 6,  7]])

## Arithmatics with Numpy

In [95]:
a

array([10,  2,  3,  4, 30,  6, 20])

In [96]:
a - 10

array([ 0, -8, -7, -6, 20, -4, 10])

In [97]:
a ** 4

array([ 10000,     16,     81,    256, 810000,   1296, 160000],
      dtype=int32)

In [98]:
a // 3

array([ 3,  0,  1,  1, 10,  2,  6], dtype=int32)

In [99]:
a

array([10,  2,  3,  4, 30,  6, 20])

In [101]:
b = a + 10
b

array([20, 12, 13, 14, 40, 16, 30])

In [102]:
a + b

array([30, 14, 16, 18, 70, 22, 50])

In [103]:
c = np.array([1,2,3])
c

array([1, 2, 3])

In [104]:
a + c

ValueError: operands could not be broadcast together with shapes (7,) (3,) 

In [105]:
arr

array([[8, 9],
       [8, 9],
       [5, 6]])

In [106]:
arr_2 = arr + 10
arr_2

array([[18, 19],
       [18, 19],
       [15, 16]])

In [107]:
arr_2 ** arr

array([[-1864941312,   565150579],
       [-1864941312,   565150579],
       [     759375,    16777216]])

In [108]:
arr3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [110]:
arr4 = arr3 + 15
arr4

array([[[16, 17, 18],
        [19, 20, 21]],

       [[22, 23, 24],
        [25, 26, 27]],

       [[28, 29, 30],
        [31, 32, 33]]])

In [111]:
arr4 // arr3

array([[[16,  8,  6],
        [ 4,  4,  3]],

       [[ 3,  2,  2],
        [ 2,  2,  2]],

       [[ 2,  2,  2],
        [ 1,  1,  1]]])

## Broadcasting

In [112]:
arr

array([[8, 9],
       [8, 9],
       [5, 6]])

In [113]:
a = np.array([1,-1])
a

array([ 1, -1])

In [114]:
arr + a

array([[9, 8],
       [9, 8],
       [6, 5]])

In [116]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [117]:
arr + a

ValueError: operands could not be broadcast together with shapes (3,2) (3,) 

## Boolean Indexing

In [118]:
a

array([1, 2, 3])

In [120]:
a[[True, False, True]]

array([1, 3])

In [122]:
bool_arr = a > 2
bool_arr

array([False, False,  True])

In [123]:
a[bool_arr]

array([3])

In [124]:
a[ a != 2 ]

array([1, 3])

In [125]:
arr

array([[8, 9],
       [8, 9],
       [5, 6]])

In [127]:
arr[ arr < 8 ]

array([5, 6])

In [126]:
arr < 8

array([[False, False],
       [False, False],
       [ True,  True]])

In [128]:
arr3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [129]:
arr3 > 10

array([[[False, False, False],
        [False, False, False]],

       [[False, False, False],
        [False,  True,  True]],

       [[ True,  True,  True],
        [ True,  True,  True]]])

In [130]:
arr3[ arr3 > 10 ]

array([11, 12, 13, 14, 15, 16, 17, 18])

In [131]:
arr3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [133]:
(arr3 > 10) & (arr3%2 == 0)

array([[[False, False, False],
        [False, False, False]],

       [[False, False, False],
        [False, False,  True]],

       [[False,  True, False],
        [ True, False,  True]]])

In [135]:
arr3[(arr3 > 10) | (arr3%2 == 0)]

array([ 2,  4,  6,  8, 10, 11, 12, 13, 14, 15, 16, 17, 18])

In [136]:
~(arr3 > 5)

array([[[ True,  True,  True],
        [ True,  True, False]],

       [[False, False, False],
        [False, False, False]],

       [[False, False, False],
        [False, False, False]]])

In [138]:
arr3[~(arr3 > 5)]

array([1, 2, 3, 4, 5])

<h1 style="font-size:30px; color:darkblue; text-align:center;">
    END</h1>