In [4]:
import numpy as np

<br> </br>

# Universal Functions (ufuncs)

<br> </br>

## Unary ufuncs

In [5]:
a1 = np.arange(1,5)
a1

array([1, 2, 3, 4])

In [7]:
np.square(a1)

array([ 1,  4,  9, 16])

In [9]:
np.sqrt(a1).round(2)

array([1.  , 1.41, 1.73, 2.  ])

In [10]:
np.exp(a1)

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

## Binary ufuncs

In [11]:
a1

array([1, 2, 3, 4])

In [13]:
b = np.arange(4,0, -1)
b

array([4, 3, 2, 1])

In [14]:
np.add(a1, b)

array([5, 5, 5, 5])

In [15]:
np.multiply(a1, b)

array([4, 6, 6, 4])

In [16]:
np.power(a1, b)

array([1, 8, 9, 4])

In [17]:
a1

array([1, 2, 3, 4])

In [18]:
b

array([4, 3, 2, 1])

In [19]:
np.maximum(a1, b)

array([4, 3, 3, 4])

# Some methods for boolean arrays

In [21]:
bool_arr = (a1 > 2)
bool_arr

array([False, False,  True,  True])

In [22]:
np.sum(bool_arr)

2

In [23]:
np.any(bool_arr)

True

In [24]:
np.all(bool_arr)

False

In [25]:
np.all([True, True, True])

True

In [26]:
bool_arr

array([False, False,  True,  True])

In [28]:
np.sum(bool_arr) >= 1

True

In [33]:
np.sum([True, True, True, True]) == bool_arr.size

True

# Sorting Numpy arrays

In [36]:
a3 = np.arange(4,0, -1)
a3

array([4, 3, 2, 1])

In [38]:
np.sort(a3)[::-1]

array([4, 3, 2, 1])

In [40]:
x = a3.sort()
type(x)

NoneType

In [42]:
a3.sort()

In [43]:
a3

array([1, 2, 3, 4])

In [47]:
a4 = np.arange(12, 0, -1).reshape(3,4)
a4

array([[12, 11, 10,  9],
       [ 8,  7,  6,  5],
       [ 4,  3,  2,  1]])

In [48]:
np.sort(a4, axis = 1)

array([[ 9, 10, 11, 12],
       [ 5,  6,  7,  8],
       [ 1,  2,  3,  4]])

In [49]:
np.sort(a4, axis = 0)

array([[ 4,  3,  2,  1],
       [ 8,  7,  6,  5],
       [12, 11, 10,  9]])

# Unique values in array

In [51]:
a5 = np.array([4,4,3,1,2,1,0])
a5

array([4, 4, 3, 1, 2, 1, 0])

In [52]:
np.unique(a5)

array([0, 1, 2, 3, 4])

In [53]:
a4

array([[12, 11, 10,  9],
       [ 8,  7,  6,  5],
       [ 4,  3,  2,  1]])

In [54]:
np.unique(a4)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

# Concatinating arrays

In [69]:
arr1 = np.arange(1,7).reshape(2,3)
arr2 = np.arange(7,13).reshape(2,3)
arr1, arr2

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 7,  8,  9],
        [10, 11, 12]]))

In [56]:
np.concatenate( [arr1, arr2], axis = 0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [57]:
np.concatenate( [arr2, arr1], axis = 0)

array([[ 7,  8,  9],
       [10, 11, 12],
       [ 1,  2,  3],
       [ 4,  5,  6]])

In [61]:
np.concatenate( [arr1, arr2, arr1], axis = 1)

array([[ 1,  2,  3,  7,  8,  9,  1,  2,  3],
       [ 4,  5,  6, 10, 11, 12,  4,  5,  6]])

In [62]:
a4

array([[12, 11, 10,  9],
       [ 8,  7,  6,  5],
       [ 4,  3,  2,  1]])

In [64]:
arr1 = arr1.reshape(3,2)
arr1

array([[1, 2],
       [3, 4],
       [5, 6]])

In [66]:
np.concatenate([a4, arr1], axis = 1)

array([[12, 11, 10,  9,  1,  2],
       [ 8,  7,  6,  5,  3,  4],
       [ 4,  3,  2,  1,  5,  6]])

In [70]:
np.vstack([arr1, arr2])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [71]:
np.hstack((arr2, arr1))

array([[ 7,  8,  9,  1,  2,  3],
       [10, 11, 12,  4,  5,  6]])

# Splitting arrays

In [72]:
a7 = np.arange(1,19).reshape(6,3)
a7

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [77]:
l = np.split(a7, [1, 3, 5])
type(l)

list

In [78]:
len(l)

4

In [79]:
l

[array([[1, 2, 3]]),
 array([[4, 5, 6],
        [7, 8, 9]]),
 array([[10, 11, 12],
        [13, 14, 15]]),
 array([[16, 17, 18]])]

In [80]:
np.split(a7, 3)

[array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 7,  8,  9],
        [10, 11, 12]]),
 array([[13, 14, 15],
        [16, 17, 18]])]

In [83]:
np.array_split(a7, 4)

[array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 7,  8,  9],
        [10, 11, 12]]),
 array([[13, 14, 15]]),
 array([[16, 17, 18]])]

<h1 style="font-size:30px; text-align:center;">
    END</h1>