In [1]:
import numpy as np

<br> </br>

In [2]:
np.array([1,2,3])

array([1, 2, 3])

In [3]:
np.array((1,2,3))

array([1, 2, 3])

In [4]:
np.array(range(4))

array([0, 1, 2, 3])

In [5]:
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [6]:
type(a1)

numpy.ndarray

In [9]:
a1.size  # it gives the total no of values in our numpy array

3

In [10]:
a1.shape

(3,)

In [11]:
a1.ndim

1

In [12]:
a1.dtype

dtype('int32')

In [15]:
a1.astype('bool')

array([ True,  True,  True])

In [16]:
a1

array([1, 2, 3])

In [17]:
np.array([
    [1,2],
    [3,4]
])

array([[1, 2],
       [3, 4]])

In [19]:
a2 = np.array([
    [1,2],
    [3,4]
])
a2

array([[1, 2],
       [3, 4]])

In [20]:
a2.ndim

2

In [21]:
a2.size

4

In [22]:
a2.shape

(2, 2)

In [23]:
np.array([
    [
        [1,2],
        [3,4]
    ],
    [
        [5,6],
        [7,8]
    ]
])

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [24]:
a3 = np.array([
    [
        [1,2],
        [3,4]
    ],
    [
        [5,6],
        [7,8]
    ]
])
a3

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [25]:
a3.ndim

3

In [26]:
a3.size

8

In [27]:
a3.shape

(2, 2, 2)

<br> </br>

#### using np.arange()

In [31]:
np.arange(2,10,3)

array([2, 5, 8])

#### using np.linspace()

In [32]:
np.linspace(1, 10, 5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [38]:
np.linspace(3,7,4)

array([3.        , 4.33333333, 5.66666667, 7.        ])

#### using np.zeros(), np.ones(), np.full()

In [33]:
np.zeros((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [35]:
np.ones((5,1))

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [36]:
np.full((3,4), 3.14)

array([[3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14]])

In [37]:
np.full((2,3,2), 2)

array([[[2, 2],
        [2, 2],
        [2, 2]],

       [[2, 2],
        [2, 2],
        [2, 2]]])

<br> </br>

<br> </br>

# Reshaping Numpy arrays

<br> </br>

#### .reshape()

In [60]:
a4 = np.arange(1,7)
a4

array([1, 2, 3, 4, 5, 6])

In [61]:
a4.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [63]:
a4.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [66]:
a4.reshape(3,2, order = 'F')

array([[1, 2],
       [3, 4],
       [5, 6]])

#### .ravel()

In [67]:
a5 = np.arange(1,7).reshape(3,2)
a5

array([[1, 2],
       [3, 4],
       [5, 6]])

In [68]:
a5.ravel()

array([1, 2, 3, 4, 5, 6])

In [69]:
a5.ravel(order = 'F')

array([1, 3, 5, 2, 4, 6])

#### .flatten()

In [70]:
a5

array([[1, 2],
       [3, 4],
       [5, 6]])

In [71]:
a5.flatten()

array([1, 2, 3, 4, 5, 6])

In [72]:
a5.flatten(order = 'F')

array([1, 3, 5, 2, 4, 6])